general.import = ["/home/andres/.config/alacritty/gruvbox.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "None"
opacity = 0.95
